Run test cases with Ruby 3.0 & 3.1
theforeman/smart_proxy_omaha pull request #24
Opened 2023-03-01 07:11 UTC by archanaserver

2023-03-01 08:06 UTC, archanaserver commented
closed by mistake

2023-03-01 08:26 UTC, archanaserver commented
This is the error I'm facing and need help with:
```
home/akumari/Desktop/smart_proxy_omaha/test/omaha/omaha_api_test.rb:154:in `test_get_releases'
     151: 
     152:   def test_get_releases
     153:     get "/tracks/alpha/amd64-usr"
  => 154:     assert last_response.ok?, "Last response was not ok: #{last_response.status} #{last_response.body}"
     155:     parsed = JSON.parse(last_response.body)
     156:     assert_kind_of Array, parsed
     157:     assert_equal ['1068.9.0', '1122.2.0'], parsed.map { |track| track['name'] }
=============================================================================================================
.................................
Finished in 0.124123959 seconds.
-------------------------------------------------------------------------------------------------------------
40 tests, 113 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
97.5% passed
-------------------------------------------------------------------------------------------------------------
322.26 tests/s, 910.38 assertions/s
rake aborted!
```

2023-03-14 12:26 UTC, archanaserver commented
> If you dive a bit deeper into the HTML it starts with:
> 
> ```
>           <h1><strong>TypeError</strong> at <strong>&#x2F;tracks&#x2F;alpha&#x2F;amd64-usr
>             </strong></h1>
>           <h2>no implicit conversion of nil into String</h2>
>           <ul>
>             <li class="first"><strong>file:</strong> <code>
>               release.rb</code></li>
>             <li><strong>location:</strong> <code>join
>               </code></li>
>             <li class="last"><strong>line:
>               </strong> 22</li>
>           </ul>
> ```
> 
> So it's this line:
> 
> https://github.com/theforeman/smart_proxy_omaha/blob/1de3a98e65cd4e376cc4c7d86b0328619a52cbe6/lib/smart_proxy_omaha/release.rb#L22
> 
> Something there is `nil` instead of a `String`.
> 
> On a related note: I'd also look at cleaning up `Gemfile` and raise the minimum Ruby version in `gemspec`, but I can imagine you first want things to work. Though I wonder why rake 10 even works because I recall that never worked for me on Ruby 3.

Thanks @ekohl, this helped.

2023-03-14 12:43 UTC, ekohl requested changes
You can also drop `if RUBY_VERSION > '1.8.7'` in `Gemfile`.

2023-03-14 12:43 UTC, ekohl commented on Gemfile
>    gem 'rack', '>= 1.1'
These are redundant since smart-proxy already depends on them:
https://github.com/theforeman/smart-proxy/blob/fba49ab1eb9bbe383572575309558ff628f5de60/smart_proxy.gemspec#L20
```suggestion
```

2023-03-14 12:43 UTC, ekohl commented on Gemfile
>    gem 'single_test'
I'd also drop this. I think we can already do so and the gem is unmaintained (last release in 2013, last commit in 2017).

2023-03-14 12:43 UTC, ekohl commented on Gemfile
> +  gem 'rack-test'
Listing this both here and in the gemspec looks redundant.

2023-03-14 12:43 UTC, ekohl commented on Gemfile
> +  gem 'nokogiri'
This is already a runtime dependency so redundant:
```suggestion
```

2023-03-14 12:43 UTC, ekohl commented on test/omaha/omaha_api_test.rb
> +    )
I think you can simplify it:
```suggestion
    Proxy::Omaha::Plugin.load_test_settings(contentpath: @contentpath)
```

2023-03-14 12:43 UTC, ekohl commented on test/omaha/omaha_api_test.rb
> +    @contentpath = Dir.mktmpdir
You should remove this in a `teardown` method. Otherwise you end up with lots of temporary directories.

2023-03-16 10:36 UTC, ekohl commented
It looks like this project still uses the old build config:
https://github.com/theforeman/jenkins-jobs/blob/5e2b1564b7c7c7cfb4da35cdbd26b52242e81110/theforeman.org/yaml/jobs/smart-proxy-plugin-pull-request.yaml#L43

The new jobs are configured here:
https://github.com/theforeman/jenkins-jobs/blob/master/theforeman.org/yaml/jobs/tests/smart-proxy-plugin-pr-test.yaml

That's why it's not yet really testing with Ruby 3.

It looks like we haven't converted the tests post-merge yet.

2023-03-20 11:53 UTC, ekohl commented
[test smart_proxy_omaha]

2023-03-20 11:59 UTC, ekohl requested changes

2023-03-20 11:59 UTC, ekohl commented on test/omaha/release_test.rb
> -    FileUtils.rm_rf(@contentpath)
You should keep this teardown since it cleans up. In https://github.com/theforeman/smart_proxy_omaha/pull/24/files#r1135483657 I also suggested to add the same thing to the other test.

2023-03-21 10:08 UTC, ekohl requested changes
Looks like RuboCop is unhappy.

2023-03-21 10:08 UTC, ekohl commented on test/omaha/release_repository_test.rb
> -  end
This needs to stay. In testing the common pattern is that you can have a `setup` method which runs before every test (here every method that starts with `test_`. Then you can also have a method `teardown` that's called after every test.

In this module there is a temporary directory created in `setup`, which you want to clean up in `teardown`. Otherwise you end up polluting the temporary directory.

2023-03-21 10:08 UTC, ekohl commented on Gemfile
>    gem 'smart_proxy', :git => 'https://github.com/theforeman/smart-proxy.git', :branch => 'develop'
I'd move this to `test` as well.

2023-03-22 05:31 UTC, archanaserver commented
> Looks like RuboCop is unhappy.

eh! i can see still Rubocop issue.
@ekohl how can i test rubocop locally, i can't see the this task in the list.

2023-03-22 09:02 UTC, archanaserver commented on Gemfile
>    gem 'smart_proxy', :git => 'https://github.com/theforeman/smart-proxy.git', :branch => 'develop'
@ekohl okay now i'm little confuse about the groups that we have in `Gemfile` like `:rubocop`, `:test`, `:development`. So how can we decide like which gem should be in which group?

2023-03-22 12:35 UTC, ekohl commented
>  @ekohl how can i test rubocop locally, i can't see the this task in the list.

You can run `bundle exec rubocop`.

2023-03-28 13:18 UTC, ekohl reviewed
Generally speaking I'm not a fan of adding a huge TODO file. Sometimes the fixes are smaller. Can you take a look at fixing them?

2023-03-28 13:18 UTC, ekohl commented on .rubocop.yml
> +Gemspec/RequiredRubyVersion:
Please add the required Ruby version instead. It's really small, but really helps a lot: https://github.com/theforeman/smart_proxy_discovery/blob/bf92993f81037e3dd0ec47d61cd654c07d6475bd/smart_proxy_discovery.gemspec#L21

2023-03-28 13:18 UTC, ekohl commented on .rubocop_todo.yml
> +Metrics/AbcSize:
I'd disable all Metrics in `.rubocop.yml` instead.

2023-04-03 09:14 UTC, archanaserver commented
> Generally speaking I'm not a fan of adding a huge TODO file. Sometimes the fixes are smaller. Can you take a look at fixing them?

@ekohl Yes I tried to fix few of them and disabled some.

2023-05-01 13:55 UTC, ekohl requested changes
Can you fix the duplicate definition of the test dependencies? I'd drop them from gemspec and only list them in the Gemfile.

2023-05-02 06:51 UTC, archanaserver commented
> Can you fix the duplicate definition of the test dependencies? I'd drop them from gemspec and only list them in the Gemfile.

Yes, fixed in the latest change!

2023-05-03 13:44 UTC, merged